image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf false

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore ./CassandraPrimitives.sln --verbosity minimal

build_script:
  - cmd: dotnet build --configuration Release ./CassandraPrimitives.sln

test_script:
  - cmd: dotnet test --no-build --verbosity normal --configuration Release ./CassandraPrimitives.Tests/CassandraPrimitives.Tests.csproj
