image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf false

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore ./src/CassandraLocal/CassandraLocal.sln --verbosity m

build_script:
  - cmd: dotnet build --configuration Release ./src/CassandraLocal/CassandraLocal.sln

test_script:
  - cmd: dotnet test --no-build --verbosity normal --configuration Release ./src/CassandraLocal/CassandraLocal.Tests/CassandraLocal.Tests.csproj
